server:
  context-path: /demo
  port: 8080
  tomcat:
  accesslog:
    enabled: true
  error:
    path: /custom/error

#由于Spring DevTools采用不一样的classloader的机制，
#所以会导致Dubbo Consumer Bean无法赋值到指定的@Component上，
#请使用以下规则：在 src/main/resources/META-INF/spring-devtools.properties
#在添加以下代码进行DevTools的classloader屏蔽：
#restart.exclude.target-classes=/target/classes/

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/
      name: test
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  http:
      converters:
        preferred-json-mapper: jackson
      encoding:
        charset: UTF-8
        enabled: true
      session:
        store-type: redis
        timeout: 5
  thymeleaf:
        prefix: classpath:/templates/views/
        cache: false
        mode: LEGACYHTML5

#Dubbo
#ZooKeeper
dubbo:
    registry:
        address: 127.0.0.1:2181

#  redis:
#          database: 1
#          host: localhost
#          port: 32770
#          pool:
#            max-active: 20
#info:
#  build:
#    artifact: @project.artifactId@
#    name: @project.name@
#    description: @project.description@
#    version=: @project.version@

kaptcha:
  session:
#    key: kaptcha.code
    key: code
  #border: no
  #渲染效果：水纹：WaterRipple；鱼眼：FishEyeGimpy；阴影：ShadowGimpy
  obscurificator:
    impl: com.google.code.kaptcha.impl.ShadowGimpy
  #不要噪点
  noise:
    impl: com.google.code.kaptcha.impl.NoNoise
  image:
    width: 80
    height: 37
  textproducer:
    font:
     color: blue
     size: 25
     names: 彩云,宋体,楷体,微软雅黑
    char:
      space: 3
      length: 4
  #和登录框背景颜色一致
  background:
    clear:
      from: 247,247,247
      to: 247,247,247

